services:
  app:
    build:
      context: .
      dockerfile: ./.devops/php/Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - phptdd
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./.devops/nginx/:/etc/nginx/conf.d/
    networks:
      - phptdd
networks:
  phptdd:
    driver: bridge
